In [1]:
import pandas as pd
df=pd.read_csv("laptops.csv")
df

,title,price,rating,brand,ram,storage,color,processor
0,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...","69,990",NaN,HP,16GB,512GB,Silver,Snapdragon
1,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",NaN,Apple,8GB,256GB,Indigo,NaN
2,"Acer Smartchoice Aspire One, AMD Ryzen 3-7320U...","42,990",Pure Silver,Acer,8GB,256GB,Silver,AMD
3,"Acer Aspire Lite, AMD Ryzen 3-5400U, 8 GB RAM,...","42,990",Steel Gray,Acer,RAM,512GB,Gray,AMD
4,Apple 2026 MacBook Pro Laptop with M5 Max chip...,"4,64,490",NaN,Apple,36GB,2TB,Black,NaN
...,...,...,...,...,...,...,...,...
447,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",NaN,Apple,8GB,256GB,Indigo,NaN
448,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...","69,990",NaN,HP,16GB,512GB,Silver,Snapdragon
449,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",NaN,Apple,8GB,256GB,Silver,NaN
450,Apple 2026 MacBook Pro Laptop with M5 Pro chip...,"3,42,490",NaN,Apple,24GB,2TB,Silver,NaN
451,Apple 2026 MacBook Air 13″ Laptop with M5 chip...,"1,94,990",NaN,Apple,24GB,1TB,NaN,NaN

In [3]:
df.head(10)

,title,price,rating,brand,ram,storage,color,processor
0,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...","69,990",NaN,HP,16GB,512GB,Silver,Snapdragon
1,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",NaN,Apple,8GB,256GB,Indigo,NaN
2,"Acer Smartchoice Aspire One, AMD Ryzen 3-7320U...","42,990",Pure Silver,Acer,8GB,256GB,Silver,AMD
3,"Acer Aspire Lite, AMD Ryzen 3-5400U, 8 GB RAM,...","42,990",Steel Gray,Acer,RAM,512GB,Gray,AMD
4,Apple 2026 MacBook Pro Laptop with M5 Max chip...,"4,64,490",NaN,Apple,36GB,2TB,Black,NaN
5,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",NaN,Apple,8GB,256GB,Silver,NaN
6,"Dell 15, Intel Core 13th Gen i5-1334U, FHD, 15...","69,990",NaN,Dell,16GB,512GB,Grey,Intel
7,"ASUS Vivobook 16,Smartchoice, 13th Gen, Intel ...","67,990",Silver,ASUS,16GB,512GB,Silver,Intel
8,Apple 2026 MacBook Pro Laptop with M5 Max chip...,"5,89,990",NaN,Apple,48GB,2TB,Black,NaN
9,"Dell 15 (Previously Inspiron) Laptop, 14th Gen...","62,490",NaN,Dell,16GB,NaN,Black,Intel

In [5]:
df.tail(10)

,title,price,rating,brand,ram,storage,color,processor
442,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",NaN,Apple,8GB,256GB,Indigo,NaN
443,"acer Aspire Lite,13th Gen, Intel Core i5-13420...","64,390",NaN,acer,RAM,512GB,Silver,Intel
444,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...","69,990",NaN,HP,16GB,512GB,Silver,Snapdragon
445,Apple 2026 MacBook Pro Laptop with M5 Max chip...,"5,89,990",NaN,Apple,48GB,2TB,Black,NaN
446,Apple 2026 MacBook Pro Laptop with M5 Pro chip...,"3,42,490",NaN,Apple,24GB,2TB,Silver,NaN
447,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",NaN,Apple,8GB,256GB,Indigo,NaN
448,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...","69,990",NaN,HP,16GB,512GB,Silver,Snapdragon
449,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",NaN,Apple,8GB,256GB,Silver,NaN
450,Apple 2026 MacBook Pro Laptop with M5 Pro chip...,"3,42,490",NaN,Apple,24GB,2TB,Silver,NaN
451,Apple 2026 MacBook Air 13″ Laptop with M5 chip...,"1,94,990",NaN,Apple,24GB,1TB,NaN,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 452 entries, 0 to 451
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      452 non-null    object
 1   price      444 non-null    object
 2   rating     44 non-null     object
 3   brand      452 non-null    object
 4   ram        423 non-null    object
 5   storage    409 non-null    object
 6   color      378 non-null    object
 7   processor  329 non-null    object
dtypes: object(8)
memory usage: 28.4+ KB

In [7]:
df.isnull().sum()

title          0
price          8
rating       408
brand          0
ram           29
storage       43
color         74
processor    123
dtype: int64

In [9]:
df.columns

Index(['title', 'price', 'rating', 'brand', 'ram', 'storage', 'color',
       'processor'],
      dtype='object')

In [11]:
df.duplicated().sum()

np.int64(179)

In [12]:
df=df.drop_duplicates()
df

,title,price,rating,brand,ram,storage,color,processor
0,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...","69,990",NaN,HP,16GB,512GB,Silver,Snapdragon
1,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",NaN,Apple,8GB,256GB,Indigo,NaN
2,"Acer Smartchoice Aspire One, AMD Ryzen 3-7320U...","42,990",Pure Silver,Acer,8GB,256GB,Silver,AMD
3,"Acer Aspire Lite, AMD Ryzen 3-5400U, 8 GB RAM,...","42,990",Steel Gray,Acer,RAM,512GB,Gray,AMD
4,Apple 2026 MacBook Pro Laptop with M5 Max chip...,"4,64,490",NaN,Apple,36GB,2TB,Black,NaN
...,...,...,...,...,...,...,...,...
412,DELL PRO 15 (2025) AMD Ryzen 5 7520U Quad Core...,"51,100",NaN,DELL,DDR5,512GB,Black,AMD
413,"Lenovo IdeaPad Slim 3, Intel Core i7-13620H, 1...","83,400",NaN,Lenovo,16GB,512GB,Grey,Intel
414,"HP 15 Business Edition (2025), Intel Core i3 1...","65,990",NaN,HP,16GB,NaN,Silver,Intel
430,"Dell 15 (Previously Inspiron), Intel Core i7 1...","82,990",NaN,Dell,16GB,512GB,Silver,Intel
436,Apple 2026 MacBook Pro Laptop with M5 Pro chip...,"3,67,900",NaN,Apple,24GB,2TB,Black,NaN

In [23]:
df.shape

(273, 8)

In [17]:
df = df.copy()

df["rating"] = df["rating"].replace("N/A", pd.NA)

df["rating"] = df["rating"].fillna(df["rating"].mode()[0])

df["rating"]

0      Get it faster
1      Get it faster
2        Pure Silver
3         Steel Gray
4      Get it faster
           ...
412    Get it faster
413    Get it faster
414    Get it faster
430    Get it faster
436    Get it faster
Name: rating, Length: 273, dtype: object

In [20]:
df = df.copy()
# df["ram"] = df["rating"].replace("N/A", pd.NA)
df["ram"] = df["ram"].fillna(df["ram"].mode()[0])
df["ram"]

0      16GB
1       8GB
2       8GB
3       RAM
4      36GB
       ...
412    DDR5
413    16GB
414    16GB
430    16GB
436    24GB
Name: ram, Length: 273, dtype: object

In [26]:
df=df.copy()
df["storage"] = df["storage"].fillna(df["storage"].mode()[0])
df["storage"]

0      512GB
1      256GB
2      256GB
3      512GB
4        2TB
       ...
412    512GB
413    512GB
414    512GB
430    512GB
436      2TB
Name: storage, Length: 273, dtype: object

In [27]:
df=df.copy()
df["color"] = df["color"].fillna(df["color"].mode()[0])
df["color"]

0      Silver
1      Indigo
2      Silver
3        Gray
4       Black
        ...
412     Black
413      Grey
414    Silver
430    Silver
436     Black
Name: color, Length: 273, dtype: object

In [28]:
df=df.copy()
df["processor"] = df["processor"].fillna(df["processor"].mode()[0])
df["processor"]

0      Snapdragon
1           Intel
2             AMD
3             AMD
4           Intel
          ...
412           AMD
413         Intel
414         Intel
430         Intel
436         Intel
Name: processor, Length: 273, dtype: object

In [32]:
df = df.copy()

# Convert price to numeric
df["price"] = pd.to_numeric(
    df["price"].str.replace(",", "", regex=False),
    errors="coerce"
)

# Fill missing prices with mean
df["price"] = df["price"].fillna(df["price"].mean())

df["price"]

0       69990.0
1       73990.0
2       42990.0
3       42990.0
4      464490.0
         ...
412     51100.0
413     83400.0
414     65990.0
430     82990.0
436    367900.0
Name: price, Length: 273, dtype: float64

In [33]:
df.isnull().sum()

title        0
price        0
rating       0
brand        0
ram          0
storage      0
color        0
processor    0
dtype: int64

In [35]:
df.to_csv("cleaned_data.csv", index=False)
print("Data saved successfully!")

Data saved successfully!